#!/bin/bash

set -ex

curl -LsSf https://astral.sh/uv/install.sh | sh
source $HOME/.local/bin/env

git clone https://github.com/qtile/qtile
cd qtile

uv sync --python="$1" --all-extras
uv run --python="$1" libqtile/backend/wayland/cffi/build.py
uv tool install .
uv tool install --reinstall ".[wayland]" # reinstall with wayland deps

# chown runner:users /home/runner/qtile -R
sudo usermod -aG video runner
