#!/usr/bin/env bash

export DISPLAY=:99
sudo Xvfb -ac $DISPLAY -screen 0 1280x1024x24 &>/dev/null &

export logfile=qtile-py"$1".log
qtile start -p "$logfile" &

echo "while ! (qtile cmd-obj -f qtile_info &>/dev/null); do echo socket not responsive yet; pidof qtile; sleep 1; done" >wait_for_socket.sh
timeout 30 bash wait_for_socket.sh
[[ $? -eq 124 ]] && echo "could not connect to socket, qtile is not running" && ls "$logfile" && tail "$logfile" && exit 1

qtile cmd-obj -f qtile_info
cargo test --lib -q -- --nocapture || export FAIL=1

pkill -9 qtile
if [[ $FAIL -eq 1 ]]; then exit 1; fi
