name: Release

on:
  push:
    tags:
      - 'v*'

env:
  # Node.js 20 is deprecated. Force Node.js 24 for all JavaScript actions.
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Release Binary
    runs-on: qtile
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Release Build
        run: cargo build --release

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          files: target/release/qticc
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
