name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release Binary
    runs-on: qtile
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Release Build
        run: cargo build --release

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/qticc
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
