name: Rust
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    # runs-on: ubuntu-24.04
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Start seatd
      run: |
        sudo seatd -g video &
    # - name: Rust Cargo cache
    #   uses: raviqqe/cargo-cache@v1
    - name: Build
      run: cargo build -q
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests on X11
      run: ./scripts/run-x11-tests
    - name: Run tests on wayland
      run: ./scripts/run-wl-tests
