name: Rust
# defaults:
#   run:
#     shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  AGENT_TOOLSDIRECTORY: "/opt/hostedtoolcache"
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  build-and-test:
    runs-on: qtile-runner-set
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup env
      shell: bash
      run: |
        echo CARGO_TARGET_DIR="$AGENT_TOOLSDIRECTORY"/cargo/target >> ${{ github.env }}
        echo CARGO_HOME="$AGENT_TOOLSDIRECTORY"/cargo >> ${{ github.env }}
        echo RUSTUP_HOME="$AGENT_TOOLSDIRECTORY"/rustup >> ${{ github.env }}
    - name: Install deps
      run: |
        ./scripts/install-deps $(cat ./deps)
    - name: Install qtile
      run: |
        ./scripts/install-qtile ${{ matrix.python-version }}
    - name: Source Cargo env and persist
      run: |
        source "$CARGO_HOME/env"
        echo "PATH=$PATH" >> ${{ github.env }}
    - name: Build
      run: |
        cd /home/runner/_work/qtile-cmd-client/qtile-cmd-client &&
          cargo build -q
    - name: Start seatd
      run: |
        sudo seatd -g video &
    - name: Run tests on X11
      run: ./scripts/run-x11-tests ${{ matrix.python-version }}
    - name: Run tests on wayland
      run: ./scripts/run-wl-tests ${{ matrix.python-version }}
